system = LibrarySystem()
system.add_library_branch("B001", "Main Library", "9am-8pm")
system.add_book("001", "The Silent Patient", "Alex Michaelides", "Mystery", 5, "Physical")
system.add_book("002", "Project Hail Mary", "Andy Weir", "Science Fiction", 2, "Digital")
system.register_member("LM001", "John Smith", "john@example.com", "Premium")
