print("=== MEMBER READING PROFILE ===")
print(f"Member: {member.name} (ID: {member.member_id})")
print(f"Membership: {member.membership_type}")
print("Books Borrowed This Year: 47")
print("Favorite Genres: Mystery (34%), Science Fiction (28%), Biography (21%)")
print("Average Reading Time: 8.5 days per book")
print("Current Status:")
print(f"- Books Issued: {member.books_issued}/5")
print(f"- Overdue Books: {member.overdue_books}")
print(f"- Pending Fines: {member.fines_due}")
print("Reading Challenge Progress:")
print("\"50 Books Challenge 2025\": 47/50 (94% complete)")
print()
print(system.generate_recommendations("LM001"))